# Project information
site_name: 'Colyseus 0.12.x'
site_description: 'Documentation for Colyseus Multiplayer Game Server for Node.js'
site_author: 'Endel Dreyer'
site_url: 'https://colyseus.io/'
edit_uri: 'https://github.com/colyseus/docs/edit/master/docs/'

# Deployment
remote_name: 'origin'
remote_branch: 'gh-pages'

# Repository
repo_name: 'colyseus/colyseus'
repo_url: 'https://github.com/colyseus/colyseus'

# Copyright
copyright: 'Copyright &copy; 2019 Endel Dreyer'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo-white.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - 'stylesheets/code-tabs.css'
  - 'stylesheets/ads.css'

extra_javascript:
  - 'javascripts/main.js'
  - 'javascripts/ads.js'

# Options
extra:
  search:
    language: 'en'
  social:
  - type: 'money'
    link: 'https://www.patreon.com/endel'
  - type: 'comments'
    link: 'https://discuss.colyseus.io'
  - type: 'globe'
    link: 'http://colyseus.io'
  - type: 'github'
    link: 'https://github.com/colyseus'
  - type: 'twitter'
    link: 'https://twitter.com/colyseus'
  - type: 'linkedin'
    link: 'https://www.linkedin.com/company/game-std-io/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'

# Nav menu
nav:
- '主页': 'index.md'
- '入门':
  - '服务器段': 'getting-started/server.md'
  - 'JavaScript 客户端': 'getting-started/javascript-client.md'
  - 'Unity3d 客户端': 'getting-started/unity3d-client.md'

- "如何使用":
  - '用密码保护房间': 'how-to/password-protect-room.md'
  - '拒绝玩家加入房间': 'how-to/deny-player-join-a-room.md'
  - '限速': 'how-to/rate-limit.md'

- '服务器 API':
  - 'Server': 'server/api.md'
  - 'Room': 'server/room.md'
  - 'Client': 'server/client.md'
  - 'Timing events': 'server/timing-events.md'
  - 'Match-maker API': 'server/matchmaker.md'
  - 'Authentication API': 'server/authentication.md'
  - 'Presence': 'server/presence.md'
  - 'Graceful shutdown': 'server/graceful-shutdown.md'
  - 'Custom State Serialization': 'server/state-serialization.md'

- '客户端 API':
  - 'Client': 'client/client.md'
  - 'Room': 'client/room.md'

- '状态处理':
  - 'Overview': 'state/overview.md'
  - 'Schema': 'state/schema.md'
  - 'Fossil Delta (deprecated)': 'state/fossil-delta.md'

- 'Authentication': 'authentication.md'
- 'Push Notifications': 'push.md'

- 'Debugging': 'debugging.md'
- 'Deployment': 'deployment.md'
- 'Scalability': 'scalability.md'
- 'Migrating':
  - '0.12.x': 'migrating/0.12.md'
  - '0.11.x': 'migrating/0.11.md'
  - '0.10.x': 'migrating/0.10.md'
  - '0.9.x': 'migrating/0.9.md'

- 'FAQ': 'faq.md'
